version: "3"
services:
  app:
    build: ..
    restart: always
    depends_on:
      - api
  mongo:
    build:
      context: ../db
    # command: '--setParameter "logComponentVerbosity={accessControl: 5, network: 1, storage: 1}"'
    command: '--syslog'
  nginx:
    build:
      context: ../nginx
    depends_on:
      - app

